
name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Publish Docker Images'
        required: true
        default: 'Publish Docker Images'

env:
  REGISTRY: ghcr.io
  NAMESPACE: codebucket-solutions
  IMAGE_NAME: acme-manager
  TAG: ${{ github.sha }}
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Agent
        run: docker build -t ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:agent-${{ env.TAG }} -f acme-manager-agent/Dockerfile .

      - name: Tag Agent
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:agent-${{ env.TAG }} ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:agent-${{ env.VERSION }}

      - name: Publish Agent
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:agent-${{ env.TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:agent-${{ env.VERSION }}
